name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manager: [npm, yarn, pnpm]
    steps:
      - uses: actions/checkout@v4
      - name: Detect package manager
        uses: g1eny0ung/detect-nodejs-package-manager-action@main
        with:
          working-directory: ./tests/${{ matrix.manager }}
          env-name: pm
      - uses: pnpm/action-setup@v2
        if: ${{ matrix.manager == 'pnpm' }}
        name: Install pnpm
        with:
          version: 8
      - name: Install dependencies
        run: $pm install
        working-directory: ./tests/${{ matrix.manager }}
